# https://taskfile.dev

version: '2'

tasks:
  default:
    deps: [test, format]
  run:
    cmds:
      - poetry run flask run
    silent: true
    env:
      FLASK_APP: funicular
      FLASK_ENV: development
  test:
    cmds:
      - poetry run pytest -s tests/
    env:
      FLASK_ENV: test
  test:watch:
    cmds:
      - find . | entr task test
  dependencies:
    cmds:
      - poetry install
  format:
    cmds:
      - poetry run black .
  bootstrap:
    deps: [prerequisites]
    cmds:
      - task: dependencies
  prerequisites:
    deps: [prerequisites:poetry, prerequisites:entr]
  prerequisites:poetry:
    cmds:
      - echo Install poetry
      - exit 1
    silent: true
    status:
      - command -v poetry
  prerequisites:entr:
    cmds:
      - echo Install entr
      - exit 1
    silent: true
    status:
      - command -v entr